export const defaultProducts = [
    // ── BEEF ──────────────────────────────────────────────────────
    {
        id: 'beef-01', category_id: 1, 
        name_he: 'אנטריקוט טרי', name_en: 'Ribeye Steak',
        description_he: 'נתח פרמיום מהצלעות, עם שיוש מעולה ותוצאה אידיאלית על הגריל.',
        description_en: 'Premium ribeye cut, beautifully marbled, ideal for grilling.',
        price_nis: 189, weight_options: [{ label: '300g', grams: 300 }, { label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/beef/ribeye.jpg',
    },
    {
        id: 'beef-02', category_id: 1, 
        name_he: 'פילה בקר מובחר', name_en: 'Beef Tenderloin',
        description_he: 'הנתח הרך ביותר – מושלם לצלייה מהירה ולסטייק בשיטת sous vide.',
        description_en: 'The most tender cut – perfect for quick searing or sous vide.',
        price_nis: 229, weight_options: [{ label: '250g', grams: 250 }, { label: '500g', grams: 500 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/beef/tenderloin.jpg',
    },
    {
        id: 'beef-03', category_id: 1, 
        name_he: 'צלי כתף בקר', name_en: 'Chuck Roast',
        description_he: 'נתח כתף שמנמן, מומלץ לבישול ממושך בתנור או בסיר לחץ.',
        description_en: 'Fatty shoulder roast, ideal for slow cooking or pressure pot.',
        price_nis: 89, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }, { label: '2kg', grams: 2000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/beef/chuck_roast.jpg',
    },
    {
        id: 'beef-04', category_id: 1, 
        name_he: 'שפיץ צ״אק', name_en: 'Chuck Eye Roll',
        description_he: 'נתח טוסס עם טעם עשיר – מעולה לסטייק ולבישול ארוך.',
        description_en: 'Flavourful chuck eye roll – great as steak or slow cooked.',
        price_nis: 119, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/beef/chuck_eye.jpg',
    },
    {
        id: 'beef-05', category_id: 1, 
        name_he: 'כבד בקר טרי', name_en: 'Fresh Beef Liver',
        description_he: 'כבד בקר טרי ואיכותי – עשיר בברזל ונוטריאנטים חיוניים.',
        description_en: 'Fresh quality beef liver – rich in iron and essential nutrients.',
        price_nis: 59, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/beef/liver.jpg',
    },
    // ── LAMB ──────────────────────────────────────────────────────
    {
        id: 'lamb-01', category_id: 2, 
        name_he: 'צלעות כבש', name_en: 'Lamb Chops',
        description_he: 'צלעות כבש עסיסיות, מתובלות בתבלינים טריים מהבית.',
        description_en: 'Juicy lamb chops, seasoned with fresh Mediterranean spices.',
        price_nis: 149, weight_options: [{ label: '400g', grams: 400 }, { label: '800g', grams: 800 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/lamb/lamb_chops.jpg',
    },
    {
        id: 'lamb-02', category_id: 2, 
        name_he: 'קבב טלה', name_en: 'Lamb Kebab',
        description_he: 'קבב טלה הכן לצלייה – על שיפוד, פאטה ותבלינים מיוחדים.',
        description_en: 'Ready-to-grill lamb kebab with special spice blend on skewers.',
        price_nis: 79, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/lamb/lamb_kebab.jpg',
    },
    {
        id: 'lamb-03', category_id: 2, 
        name_he: 'כתף טלה שלמה', name_en: 'Whole Lamb Shoulder',
        description_he: 'כתף טלה שלמה – מומלצת לצלייה איטית בתנור, עסיסית ומפנקת.',
        description_en: 'Whole lamb shoulder – slow roast for a rich and tender result.',
        price_nis: 199, weight_options: [{ label: '1.5kg', grams: 1500 }, { label: '2.5kg', grams: 2500 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/lamb/lamb_shoulder.jpg',
    },
    {
        id: 'lamb-04', category_id: 2, 
        name_he: 'שוק כבש', name_en: 'Lamb Leg',
        description_he: 'שוק כבש מהרבה ראשונה – מושלם לאוכל חגיגי בשבת.',
        description_en: 'First-grade lamb leg – perfect for a festive Shabbat meal.',
        price_nis: 169, weight_options: [{ label: '1kg', grams: 1000 }, { label: '2kg', grams: 2000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/lamb/lamb_leg.jpg',
    },
    // ── POULTRY ───────────────────────────────────────────────────
    {
        id: 'poultry-01', category_id: 3, 
        name_he: 'שניצל עוף', name_en: 'Chicken Schnitzel',
        description_he: 'פרגיות עוף פרוסות ומוכנות לשניצל – רכות ועסיסיות לבישול ביתי.',
        description_en: 'Sliced chicken breasts ready for schnitzel – tender and juicy.',
        price_nis: 56, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/poultry/chicken_schnitzel.jpg',
    },
    {
        id: 'poultry-02', category_id: 3, 
        name_he: 'שווארמה הודו', name_en: 'Turkey Shawarma',
        description_he: 'תערובת שווארמה הודו טחונה עם תבלינייים ייחודיים של האציל.',
        description_en: 'Ground turkey shawarma blend with HaAtzil signature spices.',
        price_nis: 69, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/poultry/turkey_shawarma.jpg',
    },
    {
        id: 'poultry-03', category_id: 3, 
        name_he: 'עוף שלם טרי', name_en: 'Whole Fresh Chicken',
        description_he: 'עוף שלם גדול, מגודל ללא אנטיביוטיקה – מומלץ לתבשיל או צלייה.',
        description_en: 'Large whole chicken, antibiotic-free – great for stew or roast.',
        price_nis: 48, weight_options: [{ label: '1.2kg', grams: 1200 }, { label: '1.8kg', grams: 1800 }],
        unit: 'unit', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/poultry/whole_chicken.jpg',
    },
    {
        id: 'poultry-04', category_id: 3, 
        name_he: 'כרעיים עוף', name_en: 'Chicken Legs',
        description_he: 'כרעיים עוף שמינות – מצוינות לתנור עם עשבי תיבול.',
        description_en: 'Plump chicken legs – excellent oven-roasted with fresh herbs.',
        price_nis: 39, weight_options: [{ label: '1kg', grams: 1000 }, { label: '2kg', grams: 2000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/poultry/chicken_legs.jpg',
    },
    {
        id: 'poultry-05', category_id: 3, 
        name_he: 'חזה הודו פרוס', name_en: 'Sliced Turkey Breast',
        description_he: 'חזה הודו פרוס דק, מעולה לסנדוויצ׳ים ולבישול קל.',
        description_en: 'Thinly sliced turkey breast – great for sandwiches and light cooking.',
        price_nis: 59, weight_options: [{ label: '300g', grams: 300 }, { label: '600g', grams: 600 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/poultry/turkey_breast.jpg',
    },
    // ── PREPARED ──────────────────────────────────────────────────
    {
        id: 'prep-01', category_id: 4, 
        name_he: 'קציצות בקר הכן', name_en: 'Ready Beef Patties',
        description_he: 'קציצות בקר מתובלות, מוכנות לצלייה – מתכון הבית של האציל.',
        description_en: 'Seasoned beef patties ready to pan-fry – HaAtzil house recipe.',
        price_nis: 72, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/prepared/beef_patties.jpg',
    },
    {
        id: 'prep-02', category_id: 4, 
        name_he: 'מרינדה אנטריקוט', name_en: 'Marinated Ribeye',
        description_he: 'אנטריקוט במרינדת שום ועשבי תיבול – ישר לגריל ללא הכנה.',
        description_en: 'Ribeye in garlic and herb marinade – grill-ready, no prep needed.',
        price_nis: 199, weight_options: [{ label: '400g', grams: 400 }, { label: '800g', grams: 800 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/prepared/marinated_ribeye.jpg',
    },
    {
        id: 'prep-03', category_id: 4, 
        name_he: 'נקניקיות בקר', name_en: 'Beef Sausages',
        description_he: 'נקניקיות בקר ביתיות עם תבלינים – מושלמות לברביקיו.',
        description_en: 'Homestyle beef sausages with spices – perfect for the barbecue.',
        price_nis: 64, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/prepared/beef_sausages.jpg',
    },
    {
        id: 'prep-04', category_id: 4, 
        name_he: 'מרק עצמות', name_en: 'Beef Bone Broth Kit',
        description_he: 'עצמות מרק עם ירקות שורש לבחירתכם – בסיס מושלם למרק.',
        description_en: 'Soup bones with root vegetables – the perfect soup base.',
        price_nis: 45, weight_options: [{ label: '1kg', grams: 1000 }, { label: '2kg', grams: 2000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/prepared/bone_broth.jpg',
    },
    // ── KOSHER SPECIALS ───────────────────────────────────────────
    {
        id: 'ks-01', category_id: 5, 
        name_he: 'בשר בקר מהדרין', name_en: 'Mehadrin Beef Selection',
        description_he: 'מבחר נתחי בקר מהדרין – כשרות מחמירה עם תעודה מוכרת.',
        description_en: 'Mehadrin beef selection – strict kosher with certified documentation.',
        price_nis: 249, weight_options: [{ label: '500g', grams: 500 }, { label: '1kg', grams: 1000 }],
        unit: 'kg', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin min HaMehadrin',
        image_url: '/images/products/kosher-special/mehadrin_beef.jpg',
    },
    {
        id: 'ks-02', category_id: 5, 
        name_he: 'כבש מהדרין לר״ה', name_en: 'Mehadrin Lamb for Rosh Hashana',
        description_he: 'כבש שלם או חצי לפי המסורת – כשרות מהדרין לחגים.',
        description_en: 'Whole or half lamb per tradition – mehadrin kosher for the holidays.',
        price_nis: 899, weight_options: [{ label: 'Half', grams: 4000 }, { label: 'Whole', grams: 8000 }],
        unit: 'unit', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin min HaMehadrin',
        image_url: '/images/products/kosher-special/mehadrin_lamb.jpg',
    },
    {
        id: 'ks-03', category_id: 5, 
        name_he: 'הודו שלם לחג', name_en: 'Whole Turkey for Holiday',
        description_he: 'הודו שלם מהדרין – אידיאלי לצלייה חגיגית בחגים ובארוחות גדולות.',
        description_en: 'Whole mehadrin turkey – ideal for festive holiday roasting.',
        price_nis: 289, weight_options: [{ label: '4kg', grams: 4000 }, { label: '6kg', grams: 6000 }],
        unit: 'unit', is_available: true, is_kosher: true, kosher_cert_text: 'Badatz Mehadrin',
        image_url: '/images/products/kosher-special/whole_turkey.jpg',
    },
];
